version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patches:
        patterns:
          - "*"
        update-types:
          - "patch"
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "java8"
    labels:
      - "java8"
    groups:
      patches:
        patterns:
          - "*"
        update-types:
          - "patch"
